-- MySQL Script generated by MySQL Workbench
-- Sun Nov 18 15:38:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stock_management
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stock_management` ;

-- -----------------------------------------------------
-- Schema stock_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock_management` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema stock_management
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stock_management` ;

-- -----------------------------------------------------
-- Schema stock_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock_management` DEFAULT CHARACTER SET utf8 ;
USE `stock_management` ;

-- -----------------------------------------------------
-- Table `stock_management`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`account` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`account` (
  `ACCOUNT_ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ACCOUNT_FULLNAME` VARCHAR(40) NOT NULL,
  `ACCOUNT_USERNAME` VARCHAR(16) NOT NULL,
  `ACCOUNT_PASSWORD` VARCHAR(16) NOT NULL,
  `ACCOUNT_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ACCOUNT_ID`),
  UNIQUE INDEX `ACCOUNT_USERNAME_UNIQUE` (`ACCOUNT_USERNAME` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock_management`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`supplier` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`supplier` (
  `SUPPLIER_ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `SUPPLIER_NAME` VARCHAR(45) NOT NULL,
  `SUPPLIER_CODE` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`SUPPLIER_ID`),
  UNIQUE INDEX `SUPPLIER_CODE_UNIQUE` (`SUPPLIER_CODE` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock_management`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`category` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`category` (
  `CATEGORY_ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `CATEGORY_NAME` VARCHAR(45) NOT NULL,
  `CATEGORY_CODE` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`CATEGORY_ID`),
  UNIQUE INDEX `CATEGORY_CODE_UNIQUE` (`CATEGORY_CODE` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock_management`.`producer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`producer` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`producer` (
  `PRODUCER_ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `PRODUCER_NAME` VARCHAR(45) NOT NULL,
  `PRODUCER_CODE` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`PRODUCER_ID`),
  UNIQUE INDEX `PRODUCER_CODE_UNIQUE` (`PRODUCER_CODE` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock_management`.`goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`goods` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`goods` (
  `GOODS_ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `GOODS_CODE` VARCHAR(8) NOT NULL,
  `GOODS_NAME` VARCHAR(64) NOT NULL,
  `GOODS_NEW_BRAND` INT(11) NOT NULL DEFAULT 0,
  `GOODS_LOTNUMBER` VARCHAR(16) NULL,
  `GOODS_UNIT` VARCHAR(16) NOT NULL,
  `GOODS_FEATURE` VARCHAR(45) NOT NULL,
  `GOODS_EXPIRATION` DATE NOT NULL,
  `GOODS_IMPORT_PRICE` INT(11) NOT NULL DEFAULT 0,
  `GOODS_EXPORT_PRICE` INT(11) NOT NULL DEFAULT 0,
  `SUPPLIER_ID` INT(11) UNSIGNED NOT NULL,
  `CATEGORY_ID` INT(11) UNSIGNED NOT NULL,
  `PRODUCER_ID` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`GOODS_ID`),
  UNIQUE INDEX `GOODS_CODE_UNIQUE` (`GOODS_CODE` ASC),
  INDEX `fk_goods_supplier1_idx` (`SUPPLIER_ID` ASC),
  INDEX `fk_goods_category1_idx` (`CATEGORY_ID` ASC),
  INDEX `fk_goods_producer1_idx` (`PRODUCER_ID` ASC),
  CONSTRAINT `fk_goods_supplier1`
    FOREIGN KEY (`SUPPLIER_ID`)
    REFERENCES `stock_management`.`supplier` (`SUPPLIER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goods_category1`
    FOREIGN KEY (`CATEGORY_ID`)
    REFERENCES `stock_management`.`category` (`CATEGORY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goods_producer1`
    FOREIGN KEY (`PRODUCER_ID`)
    REFERENCES `stock_management`.`producer` (`PRODUCER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock_management`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`stock` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`stock` (
  `STOCK_ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `STOCK_NAME` VARCHAR(45) NOT NULL,
  `STOCK_CODE` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`STOCK_ID`),
  UNIQUE INDEX `STOCK_CODE_UNIQUE` (`STOCK_CODE` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock_management`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`inventory` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`inventory` (
  `INVENTORY_ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `INVENTORY_QUANTITY` INT(11) NOT NULL DEFAULT 0,
  `GOODS_ID` INT(11) UNSIGNED NOT NULL,
  `STOCK_ID` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`INVENTORY_ID`),
  INDEX `fk_inventory_goods_idx` (`GOODS_ID` ASC),
  INDEX `fk_inventory_stock1_idx` (`STOCK_ID` ASC),
  CONSTRAINT `fk_inventory_goods`
    FOREIGN KEY (`GOODS_ID`)
    REFERENCES `stock_management`.`goods` (`GOODS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventory_stock1`
    FOREIGN KEY (`STOCK_ID`)
    REFERENCES `stock_management`.`stock` (`STOCK_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `stock_management` ;

-- -----------------------------------------------------
-- Table `stock_management`.`reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`reference` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`reference` (
  `REFERENCE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `REFERENCE_SECTOR` VARCHAR(8) NULL,
  `REFERENCE_NUMBERVALUE` VARCHAR(45) NULL,
  `REFERENCE_TEXTVALUE` VARCHAR(23) NULL,
  `REFERENCE_ACTIVE` INT NULL DEFAULT 1,
  PRIMARY KEY (`REFERENCE_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
